package com.monstertechno.moderndashbord.Model;

import java.util.Date;

public class Payslip {
    public String employeeContractId;
    public String code;
    public Date fromTime;
    public Date toTime;
    public Date paydayCal;
    public double salaryPerHour;
    public int standard_Work_Hours;
    public int actual_Work_Hours;
    public int ot_Hours;
    public int leave_Hours;
    public long defaultSalary;
    public int salaryType;
    public int insuranceType;
    public int insuranceAmount;
    public boolean isPersonalTaxDeduction;
    public int personalTaxDeductionAmount;
    public int dependentTaxDeductionAmount;
    public int regionType;
    public int regionMinimumWage;
    public boolean isMaternity;
    public int maternityHour;
    public int bhxH_Emp_Amount;
    public int bhyT_Emp_Amount;
    public int bhtN_Emp_Amount;
    public int bhxH_Comp_Amount;
    public int bhyT_Comp_Amount;
    public int bhtN_Comp_Amount;
    public int bhxH_Emp_Percent;
    public double bhyT_Emp_Percent;
    public int bhtN_Emp_Percent;
    public double bhxH_Comp_Percent;
    public int bhyT_Comp_Percent;
    public int bhtN_Comp_Percent;
    public int totalInsuranceEmp;
    public int totalInsuranceComp;
    public int tntt;
    public long leaveWageDeduction;
    public int taxableSalary;
    public int numberOfDependent;
    public int totalDependentAmount;
    public int totalTaxIncome;
    public int afterTaxSalary;
    public int totalDepartmentAllowance;
    public int totalContractAllowance;
    public int otWage;
    public int finalSalary;
    public Object paid_date;
    public String note;
    public String bankName;
    public String bankAcountName;
    public String bankAcountNumber;
    public Object detailTaxes;
    public String id;
}
